### ISSUE TITLE
Request: Add Walking Area etc. to Surfaces Menu

### ISSUE THREAD

**Issue by Mimonsi** [AlphaGaming7780/ELT-Surfaces#1]
In the Developer Add Options Menu there are areas that are currently unsupported by ELT-Surfaces, for example:

- Walking Area
- Park Area
- Gympark Area
- Hangaround Area
- etc.

Could you add these areas in another tab "Invisible Areas" or "Functional Areas"? They are important to use when designing functional custom parks!

**Comment by AlphaGaming7780** [comment]
Yeah, because these areas aren't surface areas.
